export { redirectTo, Navigate, Redirect } from './components/Navigate';
import { Router } from './components/Router';
export { useLocation } from './hooks/useLocation';
export { useParams } from './hooks/useParams';
export { useQuery } from './hooks/useQuery';
export { usePageNotfound } from './hooks/usePageNotfound';
export { useHash } from './hooks/useHash';
export { useHistory } from './hooks/useHistory';
export { Link } from './components/Link';
export { Route } from './components/Route';
export { RouteProps } from './contexts/routes';
export { Router };
export default Router;
