root: true

env:
  browser: true
  #node: true
  es6: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  eol-last: error
  eqeqeq: [error, allow-null]
  indent: [error, 2, { MemberExpression: 'off', SwitchCase: 1 }]
  no-trailing-spaces: error
  no-unused-vars: [error, { vars: all, args: none, ignoreRestSiblings: true }]
  no-undef: error
